Repository B07-Project-Team1/b07-project-team1, pull requests merged in 2023-08, with the labels that each got.

#16 Implement a dynamic product preview page for customers
  app/build.gradle
  app/src/main/java/com/example/b07_project_team1/MallActivity.java
  app/src/main/java/com/example/b07_project_team1/ProductPreview.java
  app/src/main/java/com/example/b07_project_team1/StoreActivity.java
  app/src/main/java/com/example/b07_project_team1/StoreAdapter.java
  app/src/main/java/com/example/b07_project_team1/model/Product.java
  app/src/main/res/drawable/preview_image_holder.xml
  app/src/main/res/drawable/product_close_button.xml
  app/src/main/res/drawable/sign_out_bold.xml
  app/src/main/res/layout/activity_product_page.xml
  app/src/main/res/layout/activity_store_detail.xml
  app/src/main/res/layout/fragment_product_preview.xml
  app/src/main/res/layout/recycler_store_product.xml
  app/src/main/res/menu/ribbon_user_icon_popup.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
Labels: enhancement

#17 Implement customer cart feature
  .idea/deploymentTargetDropDown.xml
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/b07_project_team1/CartAdapter.java
  app/src/main/java/com/example/b07_project_team1/CheckoutOrder.java
  app/src/main/java/com/example/b07_project_team1/MallActivity.java
  app/src/main/java/com/example/b07_project_team1/ProductPageActivity.java
  app/src/main/java/com/example/b07_project_team1/StoreActivity.java
  app/src/main/java/com/example/b07_project_team1/model/Order.java
  app/src/main/res/drawable/checkout_button.xml
  app/src/main/res/layout/activity_checkout_order.xml
  app/src/main/res/layout/recycler_cart_item.xml
  app/src/main/res/values/styles.xml
Labels: enhancement

#23 Implement order completion for vendors
  app/src/main/java/com/example/b07_project_team1/VendorAddProduct.java
  app/src/main/java/com/example/b07_project_team1/VendorOrderOuterAdapter.java
  app/src/main/java/com/example/b07_project_team1/VendorOrders.java
  app/src/main/java/com/example/b07_project_team1/VendorProductListing.java
  app/src/main/res/layout/activity_vendor_product_listing.xml
  app/src/main/res/layout/recycler_vendor_order.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
Labels: enhancement

#25 Implement unit tests for login module
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/b07_project_team1/CustomerCreateAccountModel.java
  app/src/main/java/com/example/b07_project_team1/CustomerCreateAccountPresenter.java
  app/src/main/java/com/example/b07_project_team1/CustomerCreateAccountView.java
  app/src/main/java/com/example/b07_project_team1/VendorCreateAccountModel.java
  app/src/main/java/com/example/b07_project_team1/VendorCreateAccountPresenter.java
  app/src/main/java/com/example/b07_project_team1/VendorCreateAccountView.java
  app/src/main/java/com/example/b07_project_team1/view/CustomerLoginView.java
  app/src/main/java/com/example/b07_project_team1/view/VendorLoginView.java
  app/src/main/res/layout/activity_customer_create_account.xml
  app/src/main/res/layout/activity_vendor_create_account.xml
  app/src/test/java/com/example/b07_project_team1/ExampleUnitTest.java
  app/src/test/java/com/example/b07_project_team1/LoginModuleTest.java
Labels: testing

#26 Implement entry flow animations and app icon
  app/src/main/ic_launcher-playstore.png
  app/src/main/java/com/example/b07_project_team1/CustomerCreateAccountPresenter.java
  app/src/main/java/com/example/b07_project_team1/CustomerCreateAccountView.java
  app/src/main/java/com/example/b07_project_team1/VendorAddProduct.java
  app/src/main/java/com/example/b07_project_team1/VendorCreateAccountPresenter.java
  app/src/main/java/com/example/b07_project_team1/VendorCreateAccountView.java
  app/src/main/java/com/example/b07_project_team1/presenter/CustomerLoginPresenter.java
  app/src/main/java/com/example/b07_project_team1/presenter/VendorLoginPresenter.java
  app/src/main/java/com/example/b07_project_team1/view/CustomerLoginView.java
  app/src/main/java/com/example/b07_project_team1/view/VendorLoginView.java
  app/src/main/res/drawable-v24/ic_launcher_foreground.xml
  app/src/main/res/drawable/ic_launcher_foreground.xml
  app/src/main/res/layout/activity_customer_create_account.xml
  app/src/main/res/layout/activity_customer_login.xml
  app/src/main/res/layout/activity_vendor_create_account.xml
  app/src/main/res/layout/activity_vendor_login.xml
  app/src/main/res/layout/animation_login_to_mall_view.xml
  app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  app/src/main/res/mipmap-hdpi/ic_launcher.webp
  app/src/main/res/mipmap-hdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-mdpi/ic_launcher.webp
  app/src/main/res/mipmap-mdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xhdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xxhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xxhdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xxxhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.webp
  app/src/main/res/values/ic_launcher_background.xml
  app/src/main/res/values/styles.xml
  app/src/main/res/xml/animation_login_to_mall_view_scene.xml
  app/src/test/java/com/example/b07_project_team1/LoginModuleTest.java
Labels: enhancement, testing

#29 Fix crash when searching in mall activity
  app/src/main/java/com/example/b07_project_team1/MallActivity.java
Labels: bug

#32 Fix null vendors being displayed in mall
  app/src/main/java/com/example/b07_project_team1/MallActivity.java
Labels: bug

#30 Adjust UI across entire application for consistency
  app/src/main/java/com/example/b07_project_team1/MallActivity.java
  app/src/main/java/com/example/b07_project_team1/ProductPageActivity.java
  app/src/main/java/com/example/b07_project_team1/StoreActivity.java
  app/src/main/java/com/example/b07_project_team1/StoreAdapter.java
  app/src/main/java/com/example/b07_project_team1/VendorSetup.java
  app/src/main/res/drawable/logout_bold.xml
  app/src/main/res/drawable/mall_ribbon_bottom.xml
  app/src/main/res/drawable/search_icon_bold.xml
  app/src/main/res/drawable/selection_plus.xml
  app/src/main/res/drawable/sign_out.xml
  app/src/main/res/drawable/sign_out_bold.xml
  app/src/main/res/layout/activity_checkout_order.xml
  app/src/main/res/layout/activity_customer_create_account.xml
  app/src/main/res/layout/activity_customer_login.xml
  app/src/main/res/layout/activity_customer_orders.xml
  app/src/main/res/layout/activity_mall_view.xml
  app/src/main/res/layout/activity_product_page.xml
  app/src/main/res/layout/activity_store_detail.xml
  app/src/main/res/layout/activity_vendor_add_product.xml
  app/src/main/res/layout/activity_vendor_create_account.xml
  app/src/main/res/layout/activity_vendor_login.xml
  app/src/main/res/layout/activity_vendor_orders.xml
  app/src/main/res/layout/activity_vendor_setup.xml
  app/src/main/res/layout/fragment_product_preview.xml
  app/src/main/res/layout/recycler_mall_stores.xml
  app/src/main/res/layout/recycler_store_product.xml
  app/src/main/res/values-night/strings.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
Labels: enhancement

#35 Fix keyboard remaining active at times
  app/src/main/java/com/example/b07_project_team1/CustomerCreateAccountView.java
  app/src/main/java/com/example/b07_project_team1/VendorAddProduct.java
  app/src/main/java/com/example/b07_project_team1/VendorCreateAccountView.java
  app/src/main/java/com/example/b07_project_team1/VendorSetup.java
  app/src/main/java/com/example/b07_project_team1/view/CustomerLoginView.java
  app/src/main/java/com/example/b07_project_team1/view/VendorLoginView.java
Labels: bug

#40 Fix crash when adding null product
  app/src/main/java/com/example/b07_project_team1/VendorAddProduct.java
Labels: bug

#41 Fix keyboard remaining active upon customer entry
  app/src/main/java/com/example/b07_project_team1/CustomerCreateAccountView.java
  app/src/main/java/com/example/b07_project_team1/view/CustomerLoginView.java
Labels: bug
